import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function AuthProvider({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <div className="page">
        <div className="side-menu">
          <button className="sidebar-button">
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </button>
          <label htmlFor="file-upload" className="sidebar-button">
            Upload Instagram Data
          </label>
          <input type="file" id="file-upload" />
          <button className="sidebar-button"> Connect to gmail</button>
          <a href="/example">
            <button className="sidebar-button"> Add example</button>
          </a>
          <a href="/">
            <button className="sidebar-button">Home</button>
          </a>
        </div>
        {children}
      </div>
    </ClerkProvider>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
